definitions:
  auth.SingUpResp:
    properties:
      token:
        description: token for authorization
        type: string
    type: object
  links.Link:
    properties:
      date:
        type: string
      link:
        type: string
      page:
        type: string
      uuid:
        type: string
    type: object
  projects.Category:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  projects.ProjectResponse:
    properties:
      cards:
        description: Project's card
        type: string
      categories:
        description: Category ids
        items:
          type: number
        type: array
      description:
        description: Project's description
        type: string
      features:
        description: Project's features
        type: string
      id:
        description: Project's id
        type: string
      photos:
        description: Project's photos
        items:
          type: number
        type: array
      subtitle:
        description: Project's subtitle
        type: string
      title:
        description: Project's title
        type: string
      url:
        description: url preview
        type: string
    type: object
  projects.ProjectsResp:
    properties:
      data:
        items:
          $ref: '#/definitions/projects.ProjectsResponse'
        type: array
    type: object
  projects.ProjectsResponse:
    properties:
      categories:
        description: Category ids
        items:
          type: number
        type: array
      id:
        description: Project's id
        type: string
      subtitle:
        description: Project's subtitle
        type: string
      title:
        description: Project's title
        type: string
      url:
        description: Url preview
        type: string
    type: object
  stat.BrowserCount:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
  stat.DateCountPair:
    properties:
      count:
        type: integer
      date:
        type: string
    type: object
  stat.NameCountPair:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
  stat.SessionResponse:
    properties:
      session:
        type: string
    type: object
  stat.SiteStats:
    properties:
      avg_duration:
        type: integer
      first_visits:
        type: integer
      top_browsers:
        items:
          $ref: '#/definitions/stat.BrowserCount'
        type: array
      top_countries:
        description: Top countries
        items:
          $ref: '#/definitions/stat.NameCountPair'
        type: array
      top_os:
        items:
          $ref: '#/definitions/stat.NameCountPair'
        type: array
      top_pages:
        items:
          $ref: '#/definitions/stat.URLCountPair'
        type: array
      total_bots:
        type: integer
      total_visits:
        type: integer
      visits_by_day:
        items:
          $ref: '#/definitions/stat.DateCountPair'
        type: array
    type: object
  stat.URLCountPair:
    properties:
      count:
        type: integer
      title:
        type: string
      url:
        type: string
    type: object
  stat.VisitsResponse:
    properties:
      data:
        $ref: '#/definitions/stat.SiteStats'
    type: object
info:
  contact: {}
paths:
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Log in to the admin panel, get a token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SingUpResp'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      tags:
      - Auth
  /api/categories:
    get:
      consumes:
      - application/json
      description: get all project categories
      parameters:
      - description: language (English by default)
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/projects.Category'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - Projects
  /api/links/to:
    get:
      description: Link redirect ( for stat )
      parameters:
      - description: the link to which the redirect will be made
        in: query
        name: link
        required: true
        type: string
      - description: the page from which the link was clicked
        in: query
        name: page
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - Links
  /api/projects:
    get:
      consumes:
      - application/json
      description: Get list Projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/projects.ProjectsResp'
        "400":
          description: Bad Request
      tags:
      - Projects
  /api/projects/{id}:
    get:
      consumes:
      - application/json
      description: Get information about the project by its ID and language, if specified
      parameters:
      - description: project ID
        in: path
        name: id
        required: true
        type: string
      - description: Project language (English by default)
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/projects.ProjectResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - Projects
  /api/stat/links:
    get:
      consumes:
      - application/json
      description: Get links statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/links.Link'
            type: array
      tags:
      - Stat
  /api/stat/update/visit:
    put:
      consumes:
      - application/json
      description: add a visit to the site, gets the IP, country, time of entry and
        uniqueness of the visit
      parameters:
      - description: Unique visit or not (0 - not unique, 1 - unique)
        in: query
        name: un
        required: true
        type: integer
      - description: UTM tag ID (optional parameter)
        in: query
        name: utm
        type: string
      - description: URL Page
        in: query
        name: url
        type: string
      - description: Title Page
        in: query
        name: title
        type: string
      - description: Session (if user yet visited website)
        in: query
        name: session
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful registration of the session and return of the session
            ID
          schema:
            $ref: '#/definitions/stat.SessionResponse'
        "400":
          description: Bad Request
      tags:
      - Stat
  /api/stat/updatevisit/extend:
    put:
      consumes:
      - application/json
      description: Extends the time spent on the site by session ID
      parameters:
      - description: Session ID
        in: query
        name: session
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Stat
  /api/stat/visits:
    get:
      consumes:
      - application/json
      description: Get information about site visits, including the number of visits,
        unique visits, top countries, top browsers and top OS
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stat.VisitsResponse'
      tags:
      - Stat
swagger: "2.0"
