definitions:
  auth.SingUpResp:
    properties:
      token:
        description: token for authorization
        type: string
    type: object
  links.Link:
    properties:
      date:
        type: string
      link:
        type: string
      page:
        type: string
      uuid:
        type: string
    type: object
  projects.Category:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  projects.ProjectResponse:
    properties:
      cards:
        description: Project's card
        type: string
      categories:
        description: Category ids
        items:
          type: number
        type: array
      description:
        description: Project's description
        type: string
      features:
        description: Project's features
        type: string
      id:
        description: Project's id
        type: string
      photos:
        description: Project's photos
        items:
          type: number
        type: array
      subtitle:
        description: Project's subtitle
        type: string
      title:
        description: Project's title
        type: string
      url:
        description: url preview
        type: string
    type: object
  projects.ProjectsResp:
    properties:
      data:
        items:
          $ref: '#/definitions/projects.ProjectsResponse'
        type: array
    type: object
  projects.ProjectsResponse:
    properties:
      categories:
        description: Category ids
        items:
          type: number
        type: array
      id:
        description: Project's id
        type: string
      subtitle:
        description: Project's subtitle
        type: string
      title:
        description: Project's title
        type: string
      url:
        description: Url preview
        type: string
    type: object
  stat.Entry:
    properties:
      count:
        description: value
        type: integer
      name:
        description: key
        type: string
    type: object
  stat.ProjectsStats:
    properties:
      count:
        description: Count visits
        type: integer
      date:
        description: Date
        type: string
      uuid:
        description: Project Id
        type: string
    type: object
  stat.SessionResponse:
    properties:
      session:
        type: string
    type: object
  stat.SiteStats:
    properties:
      avg_time_on_site:
        description: Average time spent on the site
        type: integer
      top_browsers:
        description: Top browsers
        items:
          $ref: '#/definitions/stat.Entry'
        type: array
      top_countries:
        description: Top countries
        items:
          $ref: '#/definitions/stat.Entry'
        type: array
      top_os:
        description: Top Operating systems
        items:
          $ref: '#/definitions/stat.Entry'
        type: array
      total_bots:
        description: Total bots visit
        type: integer
      total_visits:
        description: Visits
        type: integer
      total_visits_bot:
        additionalProperties:
          type: integer
        description: Total bots visit by days
        type: object
      total_visits_by_day:
        additionalProperties:
          type: integer
        description: Visits per day
        type: object
      unique_visits:
        description: Unique visits
        type: integer
      unique_visits_by_day:
        additionalProperties:
          type: integer
        description: Unique visits per day
        type: object
      visits_details_by_days:
        description: Full statistics of visits by users
        items:
          $ref: '#/definitions/stat.VisitsDetails'
        type: array
    type: object
  stat.Visits:
    properties:
      browser:
        description: Browser (Chrome, Firefox, etc.)
        type: string
      country:
        description: Short country code (EE, DE, etc.)
        type: string
      http_referer:
        description: Http Refer
        type: string
      ip:
        description: The IP address from which
        type: string
      os:
        description: Operating system (Windows, macOS, etc.)
        type: string
      platform:
        description: Platform (Linux, Macintosh, iPhone)
        type: string
      time_entry:
        description: The time at which the person entered
        type: string
      time_leaving:
        description: The time when the user left the site
        type: string
      uid:
        description: Unique identifier
        type: string
      unique:
        description: Has the user already logged in or not
        type: boolean
      utm:
        description: the UTM tag id came in
        type: string
    type: object
  stat.VisitsDetails:
    properties:
      date:
        description: Date
        type: string
      details:
        description: Details
        items:
          $ref: '#/definitions/stat.Visits'
        type: array
    type: object
  stat.VisitsResponse:
    properties:
      data:
        $ref: '#/definitions/stat.SiteStats'
    type: object
info:
  contact: {}
paths:
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Log in to the admin panel, get a token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SingUpResp'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      tags:
      - Auth
  /api/categories:
    get:
      consumes:
      - application/json
      description: get all project categories
      parameters:
      - description: language (English by default)
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/projects.Category'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - Projects
  /api/links/to:
    get:
      description: Link redirect ( for stat )
      parameters:
      - description: the link to which the redirect will be made
        in: query
        name: link
        required: true
        type: string
      - description: the page from which the link was clicked
        in: query
        name: page
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - Links
  /api/projects:
    get:
      consumes:
      - application/json
      description: Get list Projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/projects.ProjectsResp'
        "400":
          description: Bad Request
      tags:
      - Projects
  /api/projects/{id}:
    get:
      consumes:
      - application/json
      description: Get information about the project by its ID and language, if specified
      parameters:
      - description: project ID
        in: path
        name: id
        required: true
        type: string
      - description: Project language (English by default)
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/projects.ProjectResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      tags:
      - Projects
  /api/stat/links:
    get:
      consumes:
      - application/json
      description: Get links statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/links.Link'
            type: array
      tags:
      - Stat
  /api/stat/projects:
    get:
      consumes:
      - application/json
      description: Get project visits by day in 30 days
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/stat.ProjectsStats'
              type: array
            type: object
      tags:
      - Stat
  /api/stat/update/projects/{uuid}:
    put:
      consumes:
      - application/json
      description: Increments the number of project visits by 1 for the current day
      parameters:
      - description: project id
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful statistics update
      tags:
      - Stat
  /api/stat/update/visit:
    put:
      consumes:
      - application/json
      description: add a visit to the site, gets the IP, country, time of entry and
        uniqueness of the visit
      parameters:
      - description: Unique visit or not (0 - not unique, 1 - unique)
        in: query
        name: un
        required: true
        type: integer
      - description: UTM tag ID (optional parameter)
        in: query
        name: utm
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful registration of the session and return of the session
            ID
          schema:
            $ref: '#/definitions/stat.SessionResponse'
        "400":
          description: Bad Request
      tags:
      - Stat
  /api/stat/updatevisit/extend:
    put:
      consumes:
      - application/json
      description: Extends the time spent on the site by session ID
      parameters:
      - description: Session ID
        in: query
        name: session
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Stat
  /api/stat/visits:
    get:
      consumes:
      - application/json
      description: Get information about site visits, including the number of visits,
        unique visits, top countries, top browsers and top OS
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stat.VisitsResponse'
      tags:
      - Stat
swagger: "2.0"
